language: objective-c
osx_image: xcode9.2
script:
    - xcodebuild clean test -project FinancialAssistant.xcodeproj -scheme FinancialAssistantTests -destination "platform=iOS Simulator,name=iPhone 7,OS=11.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
